version: "3.7"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blogapp
      POSTGRES_USER: admin
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
